-- 11. Create Outlet Timing table

CREATE TABLE "DB514"."OUTLET_TIMING" (
    "ID"              NUMBER(*,0)
        NOT NULL ENABLE,
    "OUTLET_ID"       NUMBER(*,0)
        NOT NULL ENABLE,
    "DAY_ID"          NUMBER(*,0)
        NOT NULL ENABLE,
    "OPEN_TIME_ID"    NUMBER(*,0)
        NOT NULL ENABLE,
    "CLOSE_TIME_ID"   NUMBER(*,0)
        NOT NULL ENABLE,
    "CREATED_TIME"    DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"    DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "OUTLET_TIMING_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "OUTLET_TIMING_UK1" UNIQUE ( "OUTLET_ID","DAY_ID","OPEN_TIME_ID","CLOSE_TIME_ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "OUTLET_TIMING_FK1" FOREIGN KEY ( "OUTLET_ID" )
        REFERENCES "DB514"."OUTLET" ( "ID" )
    ENABLE,
    CONSTRAINT "OUTLET_TIMING_FK2" FOREIGN KEY ( "DAY_ID" )
        REFERENCES "DB514"."DAY_OF_WEEK" ( "ID" )
    ENABLE,
    CONSTRAINT "OUTLET_TIMING_FK3" FOREIGN KEY ( "OPEN_TIME_ID" )
        REFERENCES "DB514"."TIME_OF_DAY" ( "ID" )
    ENABLE,
    CONSTRAINT "OUTLET_TIMING_FK4" FOREIGN KEY ( "CLOSE_TIME_ID" )
        REFERENCES "DB514"."TIME_OF_DAY" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 12. Create Physical Web table

CREATE TABLE "DB514"."PHYSICAL_WEB" (
    "ID"                  NUMBER(*,0)
        NOT NULL ENABLE,
    "BEACON_ID"           NUMBER(*,0)
        NOT NULL ENABLE,
    "MESSAGE"             VARCHAR2(500 BYTE)
        NOT NULL ENABLE,
    "START_DATE"          DATE
        NOT NULL ENABLE,
    "END_DATE"            DATE
        NOT NULL ENABLE,
    "CREATED_TIME"        DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIMESTAMP"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "PHYSICAL_WEB_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "PHYSICAL_WEB_FK1" FOREIGN KEY ( "BEACON_ID" )
        REFERENCES "DB514"."BEACAON_REGISTER" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 13. Create Time of Day table

CREATE TABLE "DB514"."TIME_OF_DAY" (
    "ID"                  NUMBER(*,0)
        NOT NULL ENABLE,
    "TIME"                VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "CREATED_TIME"        DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIMESTAMP"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "TIME_OF_DAY_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 14. Create Transaction Add table

CREATE TABLE "DB514"."TRANSACTION_ADD" (
    "ID"                          NUMBER(*,0)
        NOT NULL ENABLE,
    "CUSTOMER_ID"                 NUMBER(*,0)
        NOT NULL ENABLE,
    "OUTLET_ID"                   NUMBER(*,0)
        NOT NULL ENABLE,
    "BILL_VALUE"                  NUMBER(10,2)
        NOT NULL ENABLE,
    "POINTS_BEFORE_TRANSACTION"   NUMBER(10,2)
        NOT NULL ENABLE,
    "POINTS_ADDED"                NUMBER(10,2)
        NOT NULL ENABLE,
    "POINTS_AFTER_TRANSACTION"    NUMBER(10,2)
        NOT NULL ENABLE,
    "CREATED_TIME"                DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIMESTAMP"           DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "TRANSACTION_ADD_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "TRANSACTION_ADD_FK1" FOREIGN KEY ( "CUSTOMER_ID" )
        REFERENCES "DB514"."CUSTOMER" ( "ID" )
    ENABLE,
    CONSTRAINT "TRANSACTION_ADD_FK2" FOREIGN KEY ( "OUTLET_ID" )
        REFERENCES "DB514"."OUTLET" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 15. Create Transaction Redeem table

CREATE TABLE "DB514"."TRANSACTION_REDEEM" (
    "ID"                          NUMBER(*,0)
        NOT NULL ENABLE,
    "CUSTOMER_ID"                 NUMBER(*,0)
        NOT NULL ENABLE,
    "OUTLET_ID"                   NUMBER(*,0)
        NOT NULL ENABLE,
    "BILL_VALUE"                  NUMBER(10,2)
        NOT NULL ENABLE,
    "POINTS_BEFORE_TRANSACTION"   NUMBER(10,2)
        NOT NULL ENABLE,
    "POINTS_REDEEMED"             NUMBER(10,2)
        NOT NULL ENABLE,
    "POINTS_AFTER_TRANSACTION"    NUMBER(10,2)
        NOT NULL ENABLE,
    "CREATED_TIME"                DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"                DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "TRANSACTION_REDEEM_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "TRANSACTION_REDEEM_FK1" FOREIGN KEY ( "CUSTOMER_ID" )
        REFERENCES "DB514"."CUSTOMER" ( "ID" )
    ENABLE,
    CONSTRAINT "TRANSACTION_REDEEM_FK2" FOREIGN KEY ( "OUTLET_ID" )
        REFERENCES "DB514"."OUTLET" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 16. Create Vendor table

CREATE TABLE "DB514"."VENDOR" (
    "ID"                  NUMBER(*,0)
        NOT NULL ENABLE,
    "NAME"                VARCHAR2(100 BYTE)
        NOT NULL ENABLE,
    "TYPE"                VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "IMAGE"               VARCHAR2(100 BYTE),
    "WEBSITE"             VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "CHECKIN_POINT"       NUMBER(5,2)
        NOT NULL ENABLE,
    "IS_RETIRED"          CHAR(1 BYTE) DEFAULT 'N'
        NOT NULL ENABLE,
    "CREATED_TIME"        DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"        DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "TRANSACTION_POINT"   NUMBER(5,2)
        NOT NULL ENABLE,
    CONSTRAINT "VENDOR_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE
)
    SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 17. Create Vendor Campaign table

CREATE TABLE "DB514"."VENDOR_CAMPAIGN" (
    "ID"             NUMBER(*,0)
        NOT NULL ENABLE,
    "VENDOR_ID"      NUMBER(*,0)
        NOT NULL ENABLE,
    "OUTLET_ID"      NUMBER(*,0)
        NOT NULL ENABLE,
    "TITLE"          VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "MESSAGE"        VARCHAR2(100 BYTE)
        NOT NULL ENABLE,
    "START_DATE"     DATE
        NOT NULL ENABLE,
    "END_DATE"       DATE
        NOT NULL ENABLE,
    "CREATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "VENDOR_CAMPAIGN_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "VENDOR_CAMPAIGN_FK1" FOREIGN KEY ( "VENDOR_ID" )
        REFERENCES "DB514"."VENDOR" ( "ID" )
    ENABLE,
    CONSTRAINT "VENDOR_CAMPAIGN_FK2" FOREIGN KEY ( "ID" )
        REFERENCES "DB514"."OUTLET" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 18. Create Vendor Campaign Customer table

CREATE TABLE "DB514"."VENDOR_CAMPAIGN_CUSTOMER" (
    "ID"                   NUMBER(*,0)
        NOT NULL ENABLE,
    "CUSTOMER_ID"          NUMBER(*,0)
        NOT NULL ENABLE,
    "VENDOR_CAMPAIGN_ID"   NUMBER(*,0)
        NOT NULL ENABLE,
    "SENT_DATE"            DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "VENDOR_CAMPAIGN_CUSTOMER_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "VENDOR_CAMPAIGN_CUSTOMER_FK1" FOREIGN KEY ( "VENDOR_CAMPAIGN_ID" )
        REFERENCES "DB514"."VENDOR_CAMPAIGN" ( "ID" )
    ENABLE,
    CONSTRAINT "VENDOR_CAMPAIGN_CUSTOMER_FK2" FOREIGN KEY ( "CUSTOMER_ID" )
        REFERENCES "DB514"."CUSTOMER" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;