-- 1. Create Admin User table

CREATE TABLE "DB514"."ADMIN_USER" (
    "ID"             NUMBER(*,0)
        NOT NULL ENABLE,
    "USER_NAME"      VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "PASSWORD"       VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "CREATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "ADMINUSER_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE
)
    SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;
  
  
  
-- 2. Create Android User table

CREATE TABLE "DB514"."ANDROID_USER" (
    "ID"             NUMBER(*,0)
        NOT NULL ENABLE,
    "CUSTOMER_ID"    NUMBER(*,0)
        NOT NULL ENABLE,
    "DEVICE_TYPE"    VARCHAR2(50 BYTE),
    "DEVICE_MAKE"    VARCHAR2(50 BYTE),
    "DEVICE_NAME"    VARCHAR2(50 BYTE),
    "GCM"            VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "CREATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "TABLE1_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "ANDROID_USER_FK1" FOREIGN KEY ( "CUSTOMER_ID" )
        REFERENCES "DB514"."CUSTOMER" ( "ID" )
    ENABLE
)
    SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 3. Create Beacon Register table

CREATE TABLE beacaon_register (
    id             NUMBER(*,0) NOT NULL,
    outlet_id      NUMBER(*,0) NOT NULL,
    sha1_text      VARCHAR2(50 BYTE) NOT NULL,
    namespace      VARCHAR2(50 BYTE) NOT NULL,
    instance       VARCHAR2(20 BYTE) NOT NULL,
    is_retired     CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
    created_time   DATE DEFAULT current_timestamp NOT NULL,
    updated_time   DATE DEFAULT current_timestamp NOT NULL,
    CONSTRAINT beacaon_register_pk PRIMARY KEY ( id )
        USING INDEX (
            CREATE UNIQUE INDEX beacaon_register_pk ON
                beacaon_register ( id ASC )
                    LOGGING TABLESPACE students PCTFREE 10 INITRANS 2
                        STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
                        NOPARALLEL
        )
    ENABLE
)
        LOGGING TABLESPACE students PCTFREE 10 INITRANS 1
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
        NOCOMPRESS
    NO INMEMORY
    NOPARALLEL;

ALTER TABLE beacaon_register
    ADD CONSTRAINT beacaon_register_uk1 UNIQUE ( outlet_id,namespace,instance )
        USING INDEX (
            CREATE UNIQUE INDEX beacaon_register_uk1 ON
                beacaon_register (
                    outlet_id
                ASC,
                    namespace
                ASC,
                    instance
                ASC )
                    LOGGING TABLESPACE students PCTFREE 10 INITRANS 2
                        STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
                        NOPARALLEL
        )
    ENABLE;

ALTER TABLE beacaon_register
    ADD CONSTRAINT beacaon_register_fk1 FOREIGN KEY ( outlet_id )
        REFERENCES outlet ( id )
    ENABLE;



-- 4. Create CheckIn table

CREATE TABLE check_in (
    id                      NUMBER(*,0) NOT NULL,
    customer_id             NUMBER(*,0) NOT NULL,
    outlet_id               NUMBER(*,0) NOT NULL,
    points_before_checkin   NUMBER(10,2) NOT NULL,
    checkin_points          NUMBER(10,2) NOT NULL,
    points_after_checkin    NUMBER(10,2) NOT NULL,
    created_time            DATE DEFAULT current_timestamp NOT NULL,
    updated_time            DATE DEFAULT current_timestamp NOT NULL,
    CONSTRAINT check_in_pk PRIMARY KEY ( id )
        USING INDEX (
            CREATE UNIQUE INDEX check_in_pk ON
                check_in ( id ASC )
                    LOGGING TABLESPACE students PCTFREE 10 INITRANS 2
                        STORAGE ( BUFFER_POOL DEFAULT )
                        NOPARALLEL
        )
    ENABLE
)
        LOGGING TABLESPACE students PCTFREE 10 INITRANS 1
            STORAGE ( BUFFER_POOL DEFAULT )
        NOCOMPRESS
    NO INMEMORY
    NOPARALLEL;

ALTER TABLE check_in
    ADD CONSTRAINT check_in_fk1 FOREIGN KEY ( customer_id )
        REFERENCES customer ( id )
    ENABLE;

ALTER TABLE check_in
    ADD CONSTRAINT check_in_fk2 FOREIGN KEY ( outlet_id )
        REFERENCES outlet ( id )
    ENABLE;



-- 5. Create Customer table

CREATE TABLE customer (
    id              NUMBER(*,0) NOT NULL,
    mobile          VARCHAR2(20 BYTE) NOT NULL,
    email           VARCHAR2(500 BYTE) NOT NULL,
    password        VARCHAR2(20 BYTE) NOT NULL,
    pin             NUMBER(6,0) NOT NULL,
    first_name      VARCHAR2(20 BYTE) NOT NULL,
    last_name       VARCHAR2(20 BYTE) NOT NULL,
    gender          CHAR(1 BYTE) NOT NULL,
    date_of_birth   DATE NOT NULL,
    image           VARCHAR2(100 BYTE),
    created_time    DATE DEFAULT current_timestamp NOT NULL,
    updated_time    DATE DEFAULT current_timestamp NOT NULL,
    CONSTRAINT customer_pk PRIMARY KEY ( id )
        USING INDEX (
            CREATE UNIQUE INDEX customer_pk ON
                customer ( id ASC )
                    LOGGING TABLESPACE students PCTFREE 10 INITRANS 2
                        STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
                        NOPARALLEL
        )
    ENABLE
)
        LOGGING TABLESPACE students PCTFREE 10 INITRANS 1
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
        NOCOMPRESS
    NO INMEMORY
    NOPARALLEL;

ALTER TABLE customer
    ADD CONSTRAINT customer_email_uk UNIQUE ( email )
        USING INDEX (
            CREATE UNIQUE INDEX customer_email_uk ON
                customer ( email ASC )
                    LOGGING TABLESPACE students PCTFREE 10 INITRANS 2
                        STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
                        NOPARALLEL
        )
    ENABLE;

ALTER TABLE customer
    ADD CONSTRAINT customer_mobile_uk UNIQUE ( mobile )
        USING INDEX (
            CREATE UNIQUE INDEX customer_mobile_uk ON
                customer ( mobile ASC )
                    LOGGING TABLESPACE students PCTFREE 10 INITRANS 2
                        STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED BUFFER_POOL DEFAULT )
                        NOPARALLEL
        )
    ENABLE;



-- 6. Create Customer Outstanding Summary table

CREATE TABLE "DB514"."CUSTOMER_OUTSTANDING_SUMMARY" (
    "ID"                         NUMBER(*,0)
        NOT NULL ENABLE,
    "CUSTOMER_ID"                NUMBER(*,0)
        NOT NULL ENABLE,
    "VENDOR_ID"                  NUMBER(*,0)
        NOT NULL ENABLE,
    "CHECKIN_POINTS"             NUMBER(10,2)
        NOT NULL ENABLE,
    "TRANSACTION_POINTS"         NUMBER(10,2)
        NOT NULL ENABLE,
    "TRANSACTION_ADD"            NUMBER(10,2)
        NOT NULL ENABLE,
    "TRANSACTION_REDEEM"         NUMBER(10,2)
        NOT NULL ENABLE,
    "FIRST_CHECKIN"              DATE,
    "FIRST_TRANSACTION_ADD"      DATE,
    "FIRST_TRANSACTION_REDEEM"   DATE,
    "LAST_CHECKIN"               DATE,
    "LAST_TRANSACTION_ADD"       DATE,
    "LAST_TRANSACTION_REDEEM"    DATE,
    "CHECKIN_COUNT"              NUMBER(*,0),
    "TRANS_ADD_COUNT"            NUMBER(*,0),
    "TRANS_REDEEM_COUNT"         NUMBER(*,0),
    "CREATED_TIME"               DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"               DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "CUSTOMER_SUMMARY_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "CUSTOMER_OUTSTANDING_SUMM_UK1" UNIQUE ( "CUSTOMER_ID","VENDOR_ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "CUSTOMER_OUTSTANDING_SUMM_FK1" FOREIGN KEY ( "CUSTOMER_ID" )
        REFERENCES "DB514"."CUSTOMER" ( "ID" )
    ENABLE,
    CONSTRAINT "CUSTOMER_OUTSTANDING_SUMM_FK2" FOREIGN KEY ( "VENDOR_ID" )
        REFERENCES "DB514"."VENDOR" ( "ID" )
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 7. Create Day of Week table

CREATE TABLE "DB514"."DAY_OF_WEEK" (
    "ID"             NUMBER(*,0)
        NOT NULL ENABLE,
    "DAY"            VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "CREATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "DAY_OF_WEEK_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;

CREATE OR REPLACE EDITIONABLE TRIGGER "DB514"."DAY_OF_WEEK_TRG" 
BEFORE INSERT ON DAY_OF_WEEK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT .NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DB514"."DAY_OF_WEEK_TRG" ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "DB514"."DAY_OF_WEEK_TRG1" 
BEFORE INSERT ON DAY_OF_WEEK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DAY_OF_WEEK_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DB514"."DAY_OF_WEEK_TRG1" ENABLE;



-- 8. Create Employee table

CREATE TABLE "DB514"."EMPLOYEE" (
    "ID"              VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "FIRST_NAME"      VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "LAST_NAME"       VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "EMAIL"           VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "GENDER"          CHAR(1 BYTE)
        NOT NULL ENABLE,
    "DATE_OF_BIRTH"   DATE
        NOT NULL ENABLE,
    "CREATED_TIME"    DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"    DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS TABLESPACE "STUDENTS"
    ENABLE
)
    SEGMENT CREATION DEFERRED
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "STUDENTS";

CREATE OR REPLACE EDITIONABLE TRIGGER "DB514"."EMPLOYEE_TRG" BEFORE
    INSERT ON employee
    FOR EACH ROW
BEGIN
    << column_sequences >> BEGIN
        NULL;
    END column_sequences;
END;
/

ALTER TRIGGER "DB514"."EMPLOYEE_TRG" ENABLE;



-- 9. Create IOS User table

CREATE TABLE "DB514"."IOS_USER" (
    "ID"             NUMBER(*,0)
        NOT NULL ENABLE,
    "CUSTOMER_ID"    NUMBER(*,0)
        NOT NULL ENABLE,
    "DEVICE_TYPE"    VARCHAR2(50 BYTE),
    "DEVICE_NAME"    VARCHAR2(50 BYTE),
    "GCM"            VARCHAR2(50 BYTE),
    "CREATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "IOS_USER_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "IOS_USER_FK1" FOREIGN KEY ( "CUSTOMER_ID" )
        REFERENCES "DB514"."CUSTOMER" ( "ID" )
    ENABLE
)
    SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;



-- 10. Create Outlet table

CREATE TABLE "DB514"."OUTLET" (
    "ID"             NUMBER(*,0)
        NOT NULL ENABLE,
    "VENDOR_ID"      NUMBER(*,0)
        NOT NULL ENABLE,
    "EMAIL"          VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "PASSWORD"       VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "ADDR_1"         VARCHAR2(500 BYTE)
        NOT NULL ENABLE,
    "ADDR_2"         VARCHAR2(500 BYTE),
    "CITY"           VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "STATE"          VARCHAR2(50 BYTE)
        NOT NULL ENABLE,
    "ZIP"            VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "CONTACT"        VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "IS_ADMIN"       CHAR(1 BYTE) DEFAULT 'Y'
        NOT NULL ENABLE,
    "CREATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    "UPDATED_TIME"   DATE DEFAULT current_timestamp
        NOT NULL ENABLE,
    CONSTRAINT "OUTLET_PK" PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    ENABLE,
    CONSTRAINT "OUTLET_FK" FOREIGN KEY ( "VENDOR_ID" )
        REFERENCES "DB514"."VENDOR" ( "ID" )
            ON DELETE CASCADE
    ENABLE
)
    SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "STUDENTS"
    NO INMEMORY;